# Mod Properties
mod_version = 0.0.2
mod_id = createphotomovement
mod_name = Create Photomovement
mod_license = MIT
mod_authors = User
mod_description = A Create mod addon adding a solar powered rotation source.

# Minecraft / NeoForge
minecraft_version = 1.21.1
neo_version = 21.1.206

# Dependencies
# Check Create's gradle.properties for exact versions if needed
create_version = 6.0.10-219
flywheel_version = 1.0.6
registrate_version = MC1.21-1.3.0+67
