pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.neoforged.net/releases' }
        maven { url = 'https://maven.fabricmc.net/' }
    }
}

rootProject.name = 'create-photomovement'

include 'neoforge:1201'
include 'neoforge:1211'
// include 'forge:1201'
include 'fabric:1201'


