plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.107'
}

group = 'com.createphotomovement'
version = mod_version
base.archivesName = "createphotomovement-neoforge-${minecraft_version}"

repositories {
    mavenLocal()
    mavenCentral()
    maven { url = "https://maven.createmod.net" } // Create, Ponder, Flywheel
    maven { url = "https://maven.ithundxr.dev/snapshots" } // Registrate
}

dependencies {
    implementation("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") {
        exclude group: 'dev.ftb.mods'
        exclude group: 'dev.architectury'
        exclude group: 'maven.modrinth'
        exclude group: 'cc.tweaked'
    }
    implementation "net.createmod.ponder:ponder-neoforge:${ponder_version}+mc${minecraft_version}"
    implementation "dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_version}"
    implementation "com.tterrag.registrate:Registrate:${registrate_version}"
}

neoForge {
    version = neo_version

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }

    runs {
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'forge.logging.console.level', 'debug'
        }

        client {
            client()
            programArguments.addAll '--width', '1600', '--height', '900', '--quickPlaySingleplayer', 'CPM Testwork'
        }

        server {
            server()
            programArgument '--nogui'
        }

        data {
            data()
            programArguments.addAll '--mod', mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
    }
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

// Process resources to expand gradle properties
processResources {
    def resourceTargets = [
        'META-INF/neoforge.mods.toml',
        'pack.mcmeta'
    ]
    def replaceProperties = [
        mod_id: mod_id,
        mod_version: mod_version,
        mod_name: mod_name,
        mod_license: mod_license,
        mod_authors: mod_authors,
        mod_description: mod_description,
        minecraft_version: minecraft_version,
        neo_version: neo_version
    ]
    inputs.properties replaceProperties
    filesMatching(resourceTargets) {
        expand replaceProperties
    }
}
